### ISSUE TITLE
是这个吗

### ISSUE THREAD

**Issue by Alex-Hou** [zcynine/vue-app#1]
https://github.com/zcynine/vue-app/blob/baa4c6b2ad676d94628203eb1b26b4e0287706f1/src/components/Menu.vue#L4-L23

**Comment by zcynine** [comment]
是的，我已经解决了，使用v-for、v-if、v-else解决了，注意v-for的优先级比v-if要高，所以即使v-else不在v-for的标签对内，也可以使用v-for的item。
